export const schoolRoutes={
  "s_total_total_subction":{
    path:"s_total_total_subction",
    name:"s_total_total_subction",
    component:()=>import("@/views/SchoolExamAnalyze/Total_total_subction.vue")
  },
  "s_class_group_subction":{
    path:"s_class_group_subction",
    name:"s_class_group_subction",
    component:()=>import("@/views/SchoolExamAnalyze/Class_group_subction.vue")
  },
  "s_total_class_subction":{
    path:"s_total_class_subction",
    name:"s_total_class_subction",
    component:()=>import("@/views/SchoolExamAnalyze/Total_class_subction.vue")
  },
  "s_class_avg":{
    path:"s_class_avg",
    name:"s_class_avg",
    component:()=>import("@/views/SchoolExamAnalyze/Class_avg.vue")
  },
  "s_class_height_low":{
    path:"s_class_height_low",
    name:"s_class_height_low",
    component:()=>import("@/views/SchoolExamAnalyze/Class_height_low_score.vue")
  },
  "s_total_all_ranking":{
    path:"s_total_all_ranking",
    name:"s_total_all_ranking",
    component:()=>import("@/views/SchoolExamAnalyze/Total_all_ranking.vue")
  },
  "s_total_pro_stu_class":{
    path:"s_total_pro_stu_class",
    name:"s_total_pro_stu_class",
    component:()=>import("@/views/SchoolExamAnalyze/Total_progress_student_class.vue")
  },
  "s_total_reg_stu_class":{
    path:"s_total_reg_stu_class",
    name:"s_total_reg_stu_class",
    component:()=>import("@/views/SchoolExamAnalyze/Total_regress_student_class.vue")
  },
  "s_total_score_excellent_stu":{//总分优秀学生班级分布图
    path:"s_total_score_excellent_stu",
    name:"s_total_score_excellent_stu",
    component:()=>import("@/views/SchoolExamAnalyze/Total_score_excellent_stu.vue")
  },
  "s_total_score_quasi_excellent_stu":{//总分准优秀学生班级分布图
    path:"s_total_score_quasi_excellent_stu",
    name:"s_total_score_quasi_excellent_stu",
    component:()=>import("@/views/SchoolExamAnalyze/Total_score_quasi_excellent_stu.vue")
  },
  "s_total_score_good_stu":{//总分良好学生班级分布图
    path:"s_total_score_good_stu",
    name:"s_total_score_good_stu",
    component:()=>import("@/views/SchoolExamAnalyze/Total_score_good_stu.vue")
  },
  "s_total_score_quasi_good_stu":{//总分准良好学生班级分布图
    path:"s_total_score_quasi_good_stu",
    name:"s_total_score_quasi_good_stu",
    component:()=>import("@/views/SchoolExamAnalyze/Total_score_quasi_good_stu.vue")
  },
  "s_total_score_pass_stu":{//总分及格学生班级分布图
    path:"s_total_score_pass_stu",
    name:"s_total_score_pass_stu",
    component:()=>import("@/views/SchoolExamAnalyze/Total_score_pass_stu.vue")
  },
  "s_total_score_hard_stu":{//总分学困学生班级分布图
    path:"s_total_score_hard_stu",
    name:"s_total_score_hard_stu",
    component:()=>import("@/views/SchoolExamAnalyze/Total_score_hard_stu.vue")
  },
}
